import crypto from 'node:crypto';
import {APP_ID} from './identity.mjs';
export const PACKS=[{id:'video_1',name:'1 Video',amount:999,credits:1,type:'payment'},{id:'video_3',name:'3 Videos',amount:1799,credits:3,type:'payment'},{id:'video_10',name:'10 Videos',amount:4999,credits:10,type:'payment'}];
export function createCredits(db,cfg,{fetcher=fetch,authenticator}={}){
 db.exec(`CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,created INTEGER NOT NULL,blocked INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS account_sessions(token TEXT PRIMARY KEY,account TEXT NOT NULL,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS credit_purchases(id TEXT PRIMARY KEY,owner TEXT NOT NULL,request_key TEXT NOT NULL,plan TEXT NOT NULL,amount INTEGER NOT NULL,credits INTEGER NOT NULL,type TEXT NOT NULL,checkout TEXT,customer TEXT,subscription TEXT,payment TEXT,state TEXT NOT NULL,UNIQUE(owner,request_key));
 CREATE TABLE IF NOT EXISTS credit_grants(id TEXT PRIMARY KEY,owner TEXT NOT NULL,kind TEXT NOT NULL,total INTEGER NOT NULL,remaining INTEGER NOT NULL,expires INTEGER,purchase TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS credit_spends(task TEXT PRIMARY KEY,owner TEXT NOT NULL,grant_id TEXT NOT NULL,returned INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS credit_events(id TEXT PRIMARY KEY);
 CREATE TABLE IF NOT EXISTS ledger_times(kind TEXT NOT NULL,id TEXT NOT NULL,created INTEGER NOT NULL,PRIMARY KEY(kind,id));
 CREATE TABLE IF NOT EXISTS billing_receipts(id TEXT PRIMARY KEY,purchase TEXT NOT NULL,amount INTEGER NOT NULL,created INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS credit_invoice_payments(invoice TEXT PRIMARY KEY,purchase TEXT NOT NULL,payment TEXT UNIQUE NOT NULL);
 CREATE TABLE IF NOT EXISTS credit_subscriptions(id TEXT PRIMARY KEY,owner TEXT NOT NULL,customer TEXT NOT NULL,purchase TEXT NOT NULL,status TEXT NOT NULL,cancel_at_end INTEGER NOT NULL DEFAULT 0);`);
 const plans=()=>[...PACKS,...(cfg.monthlyAmount&&cfg.monthlyCredits?[{id:'monthly',name:'Monthly',amount:cfg.monthlyAmount,credits:cfg.monthlyCredits,type:'subscription'}]:[])];
 const stamp=(kind,id,created=Date.now())=>db.prepare('INSERT OR IGNORE INTO ledger_times VALUES(?,?,?)').run(kind,id,created);
 const receipt=(id,p,event)=>{db.prepare('INSERT OR IGNORE INTO billing_receipts VALUES(?,?,?,?)').run(id,p.id,p.amount,Number.isFinite(event.created)?event.created*1000:Date.now());};
 const tx=fn=>{if(db.transaction)return db.transaction(fn);db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}};
 const resolve=token=>db.prepare('SELECT account FROM account_sessions WHERE token=? AND expires>?').get(token,Date.now())?.account||token;
 function authenticate(token,email,password,signup=false){if(authenticator)return authenticator(db,token,email,password,signup,wallet);email=String(email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||typeof password!=='string'||password.length<12||password.length>128)throw new Error('Choose a valid email and a password of 12–128 characters.');let a=db.prepare('SELECT * FROM accounts WHERE email=?').get(email);if(signup){if(a)throw new Error('Account unavailable. Sign in instead.');const salt=crypto.randomBytes(16).toString('hex');a={id:crypto.randomUUID(),email,password:salt+':'+crypto.scryptSync(password,salt,64).toString('hex')};db.prepare('INSERT INTO accounts(id,email,password,created) VALUES(?,?,?,?)').run(a.id,email,a.password,Date.now());}else{const [salt,hash]=(a?.password||'missing:'+Buffer.alloc(64).toString('hex')).split(':');const got=crypto.scryptSync(password,salt,64);if(!a||!crypto.timingSafeEqual(got,Buffer.from(hash,'hex')))throw new Error('Email or password did not match.');}db.prepare('INSERT OR REPLACE INTO account_sessions VALUES(?,?,?)').run(token,a.id,Date.now()+7*86400000);return wallet(a.id);}
 function wallet(owner){const a=db.prepare('SELECT id,email,blocked FROM accounts WHERE id=?').get(owner);const grants=db.prepare('SELECT kind,SUM(remaining) AS n FROM credit_grants WHERE owner=? AND (expires IS NULL OR expires>?) GROUP BY kind').all(owner,Date.now());return{account:a?{id:a.id,email:a.email,blocked:!!a.blocked}:null,balance:grants.reduce((n,g)=>n+g.n,0),purchased:grants.find(g=>g.kind==='pack')?.n||0,subscription:grants.find(g=>g.kind==='subscription')?.n||0,orders:db.prepare('SELECT id,state,created FROM orders WHERE owner=? ORDER BY created DESC LIMIT 20').all(owner),subscriptions:db.prepare('SELECT id,status,cancel_at_end FROM credit_subscriptions WHERE owner=?').all(owner),plans:plans(),demo:cfg.mode==='demo'};}
 function reserve(task,owner){if(!wallet(owner).account||wallet(owner).account.blocked)throw new Error('Choose an active account before generating.');const grant=db.prepare("SELECT * FROM credit_grants WHERE owner=? AND remaining>0 AND (expires IS NULL OR expires>?) ORDER BY CASE WHEN kind='subscription' THEN 0 ELSE 1 END,expires,id LIMIT 1").get(owner,Date.now());if(!grant)throw Object.assign(new Error('Choose a video pack first. Your balance is empty.'),{status:402});db.prepare('UPDATE credit_grants SET remaining=remaining-1 WHERE id=? AND remaining>0').run(grant.id);db.prepare('INSERT INTO credit_spends(task,owner,grant_id) VALUES(?,?,?)').run(task,owner,grant.id);stamp('spend',task);}
 function refund(task){return tx(()=>{const s=db.prepare('SELECT * FROM credit_spends WHERE task=? AND returned=0').get(task);if(!s)return false;db.prepare('UPDATE credit_grants SET remaining=remaining+1 WHERE id=?').run(s.grant_id);db.prepare('UPDATE credit_spends SET returned=1 WHERE task=?').run(task);stamp('refund',task);return true;});}
 async function stripe(endpoint,params,key,method='POST'){const r=await fetcher('https://api.stripe.com/v1/'+endpoint,{method,headers:{Authorization:`Bearer ${cfg.stripeKey}`,'Content-Type':'application/x-www-form-urlencoded','Stripe-Version':'2024-06-20',...(key?{'Idempotency-Key':key}:{})},...(method==='POST'?{body:new URLSearchParams(params)}:{}),signal:AbortSignal.timeout(45000)});const data=await r.json();if(!r.ok||data.error)throw new Error('Billing service unavailable.');return data;}
 async function purchase(owner,planId,key){if(!wallet(owner).account||wallet(owner).account.blocked)throw new Error('Choose an active account before purchasing.');const plan=plans().find(p=>p.id===planId);if(!plan||!/^[-a-zA-Z0-9]{16,80}$/.test(key||''))throw new Error('Choose an available video pack.');let p=db.prepare('SELECT * FROM credit_purchases WHERE owner=? AND request_key=?').get(owner,key);if(!p&&plan.type==='subscription')p=db.prepare("SELECT * FROM credit_purchases WHERE owner=? AND type='subscription' AND state='pending' LIMIT 1").get(owner);if(!p){p={id:crypto.randomUUID(),owner,plan:plan.id,amount:plan.amount,credits:plan.credits,type:plan.type};if(p.type==='subscription'&&db.prepare("SELECT id FROM credit_subscriptions WHERE owner=? AND status NOT IN ('canceled','incomplete_expired')").get(owner))throw new Error('Choose your current subscription before starting another.');db.prepare('INSERT INTO credit_purchases(id,owner,request_key,plan,amount,credits,type,state) VALUES(?,?,?,?,?,?,?,?)').run(p.id,owner,key,p.plan,p.amount,p.credits,p.type,'pending');stamp('purchase',p.id);}
 if(p.plan!==plan.id)throw new Error('Choose the same plan for this checkout request.');
 if(cfg.mode==='demo'){if(p.type!=='payment')throw new Error('Choose a one-time pack for this demo.');tx(()=>{db.prepare('INSERT OR IGNORE INTO credit_grants VALUES(?,?,?,?,?,?,?)').run('pack-'+p.id,owner,'pack',p.credits,p.credits,null,p.id);db.prepare('UPDATE credit_purchases SET state=? WHERE id=?').run('paid',p.id);});return{demo:true,wallet:wallet(owner)};}
 if(['expired','failed'].includes(p.state))throw Object.assign(new Error('Checkout expired. Choose the plan again.'),{status:409,code:'checkout_expired'});
 if(p.state==='paid')return{completed:true,wallet:wallet(owner)};
 if(p.checkout){const current=await stripe('checkout/sessions/'+p.checkout,{},null,'GET');if(current.status==='expired'){db.prepare('UPDATE credit_purchases SET state=? WHERE id=? AND state=?').run('expired',p.id,'pending');throw Object.assign(new Error('Checkout expired. Choose the plan again.'),{status:409,code:'checkout_expired'});}if(current.status==='open'&&current.url)return{url:current.url};throw new Error('Your payment is being confirmed. Check your account before starting another checkout.');}
 const params={mode:p.type,'adaptive_pricing[enabled]':'false',client_reference_id:p.id,'metadata[appId]':APP_ID,'metadata[purchaseId]':p.id,success_url:cfg.origin+'/?billing=success&purchase='+p.id,cancel_url:cfg.origin+'/?billing=cancelled','line_items[0][price_data][currency]':'usd','line_items[0][price_data][unit_amount]':String(p.amount),'line_items[0][price_data][product_data][name]':plan.name+' — Genjutsu AI Credits','line_items[0][quantity]':'1'};
 if(p.type==='subscription'){params['line_items[0][price_data][recurring][interval]']='month';params['subscription_data[metadata][appId]']=APP_ID;params['subscription_data[metadata][purchaseId]']=p.id;}else{params['payment_intent_data[metadata][appId]']=APP_ID;params['payment_intent_data[metadata][purchaseId]']=p.id;}
 if(cfg.stripePrices?.[plan.id]){for(const k of Object.keys(params))if(k.startsWith('line_items[0][price_data]'))delete params[k];params['line_items[0][price]']=cfg.stripePrices[plan.id];} params.customer_email=wallet(owner).account.email; const session=await stripe('checkout/sessions',params,'credits-'+p.id);db.prepare('UPDATE credit_purchases SET checkout=? WHERE id=?').run(session.id,p.id);return{url:session.url};
 }
 async function webhook(event){if(db.prepare('SELECT id FROM credit_events WHERE id=?').get(event.id))return;const s=event.data.object;let sub,invoice=s;
 if(['invoice.paid','invoice.payment_failed'].includes(event.type)){const sid=s.subscription||s.parent?.subscription_details?.subscription;if(typeof sid!=='string')return;sub=await stripe('subscriptions/'+sid,{},null,'GET');}
 tx(()=>{
 if(db.prepare('SELECT id FROM credit_events WHERE id=?').get(event.id))return;
 if(['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(event.type)){const p=db.prepare('SELECT * FROM credit_purchases WHERE id=?').get(s.metadata?.purchaseId);if(s.metadata?.appId===APP_ID&&p&&s.id===p.checkout&&s.client_reference_id===p.id&&s.currency==='usd'&&s.amount_total===p.amount&&s.payment_status==='paid'&&s.mode===p.type){if(p.type==='payment'&&typeof s.payment_intent==='string'){db.prepare('INSERT OR IGNORE INTO credit_grants VALUES(?,?,?,?,?,?,?)').run('pack-'+p.id,p.owner,'pack',p.credits,p.credits,null,p.id);db.prepare('UPDATE credit_purchases SET state=?,payment=? WHERE id=?').run('paid',s.payment_intent,p.id);stamp('grant','pack-'+p.id);receipt('pack-'+p.id,p,event);}else if(typeof s.subscription==='string'&&typeof s.customer==='string'){db.prepare('UPDATE credit_purchases SET subscription=?,customer=?,state=? WHERE id=?').run(s.subscription,s.customer,'active',p.id);db.prepare('INSERT OR IGNORE INTO credit_subscriptions VALUES(?,?,?,?,?,?)').run(s.subscription,p.owner,s.customer,p.id,'incomplete',0);if(typeof invoice.payment_intent==='string')db.prepare('UPDATE credit_purchases SET payment=? WHERE id=?').run(invoice.payment_intent,p.id);}}}
 if(['checkout.session.expired','checkout.session.async_payment_failed'].includes(event.type)&&s.metadata?.appId===APP_ID){const p=db.prepare('SELECT * FROM credit_purchases WHERE id=?').get(s.metadata.purchaseId);if(p&&p.checkout===s.id&&p.state==='pending')db.prepare('UPDATE credit_purchases SET state=? WHERE id=?').run(event.type==='checkout.session.expired'?'expired':'failed',p.id);}
 if(event.type==='invoice.paid'&&sub?.metadata?.appId===APP_ID){const p=db.prepare('SELECT * FROM credit_purchases WHERE id=?').get(sub.metadata.purchaseId);const line=invoice.lines?.data?.find(l=>(l.subscription===sub.id||l.parent?.subscription_item_details?.subscription===sub.id)&&!l.proration);if(!p||p.type!=='subscription'||!['active','trialing'].includes(sub.status)||invoice.customer!==sub.customer||invoice.currency!=='usd'||invoice.amount_paid!==p.amount||!['subscription_create','subscription_cycle'].includes(invoice.billing_reason)||!line?.period?.end||!line.period.start||((line.price?.unit_amount??line.pricing?.price_details?.unit_amount)!==p.amount))throw new Error('Subscription invoice requires review.');db.prepare('INSERT OR IGNORE INTO credit_grants VALUES(?,?,?,?,?,?,?)').run('invoice-'+invoice.id,p.owner,'subscription',p.credits,p.credits,line.period.end*1000,p.id);stamp('grant','invoice-'+invoice.id);receipt('invoice-'+invoice.id,p,event);db.prepare('INSERT OR REPLACE INTO credit_subscriptions VALUES(?,?,?,?,?,?)').run(sub.id,p.owner,sub.customer,p.id,sub.status,sub.cancel_at_period_end?1:0);db.prepare('UPDATE credit_purchases SET subscription=?,customer=?,state=? WHERE id=?').run(sub.id,sub.customer,'active',p.id);if(typeof invoice.payment_intent==='string')db.prepare('INSERT OR IGNORE INTO credit_invoice_payments VALUES(?,?,?)').run(invoice.id,p.id,invoice.payment_intent);}
 if(event.type==='invoice.payment_failed'&&sub?.metadata?.appId===APP_ID){const p=db.prepare('SELECT * FROM credit_purchases WHERE id=? AND subscription=?').get(sub.metadata.purchaseId,sub.id);if(p&&invoice.customer===sub.customer)db.prepare('UPDATE credit_subscriptions SET status=?,cancel_at_end=? WHERE id=?').run(sub.status,sub.cancel_at_period_end?1:0,sub.id);}
 if(event.type.startsWith('customer.subscription.')&&s.metadata?.appId===APP_ID){const p=db.prepare('SELECT * FROM credit_purchases WHERE id=? AND subscription=?').get(s.metadata.purchaseId,s.id);if(p)db.prepare('UPDATE credit_subscriptions SET status=?,cancel_at_end=? WHERE id=?').run(s.status,s.cancel_at_period_end?1:0,s.id);}
 if(['charge.refunded','charge.dispute.created'].includes(event.type)){const pi=s.payment_intent;const p=typeof pi==='string'?db.prepare('SELECT owner FROM credit_purchases WHERE payment=? UNION SELECT p.owner FROM credit_invoice_payments i JOIN credit_purchases p ON p.id=i.purchase WHERE i.payment=?').get(pi,pi):null;if(p)db.prepare('UPDATE accounts SET blocked=1 WHERE id=?').run(p.owner);}
 db.prepare('INSERT INTO credit_events VALUES(?)').run(event.id);
 });}
 async function portal(owner){const s=db.prepare('SELECT customer FROM credit_subscriptions WHERE owner=? ORDER BY rowid DESC LIMIT 1').get(owner);if(!s)throw Object.assign(new Error('There is no subscription to manage.'),{status:409,code:'no_subscription'});if(cfg.mode==='demo')throw Object.assign(new Error('Subscription management is unavailable.'),{status:503});const r=await stripe('billing_portal/sessions',{customer:s.customer,return_url:cfg.origin+'/',...(cfg.portalConfig?{configuration:cfg.portalConfig}:{})},'portal-'+owner+'-'+crypto.randomUUID());return{url:r.url};}
 return{plans,wallet,resolve,authenticate,reserve,refund,purchase,webhook,portal,logout:token=>db.prepare('DELETE FROM account_sessions WHERE token=?').run(token)};
}
